spring:
  application:
    name: e-commerce
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

admin:
  username: admin
  password: admin

server:
  port: 8082

logging:
  level:
    root: INFO
    org.hibernate: ERROR
    org.springframework.security: OFF

storage:
  root:
    folder:
      product: D:\\t3h\\e-commerce\\src\\main\\resources\\static\\image
      avatar: D:\\t3h\\images\\avatar
  relative:
    path: file/avatar/

